
Status: PASSED!
Check: 1
Test: Output is correct
Reason: None
Timestamp: 2024-11-19 03:18:10.883569

Status: PASSED!
Check: 2
Test: A `try` block was used
Reason: try` was found in the program.None
Timestamp: 2024-11-19 03:18:10.883790

Status: PASSED!
Check: 3
Test: An `except` block was used
Reason: except` was found in the program.None
Timestamp: 2024-11-19 03:18:10.883952

Status: PASSED!
Check: 4
Test: Correct error type was declared in the `except` statement
Reason: AttributeError` was found in the program.None
Timestamp: 2024-11-19 03:18:10.884106
